services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - "3200:8080"
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
    depends_on:
      - ollama
      - auto
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  auto:
    image: sd-auto:78
    build: ./services/AUTOMATIC1111
    environment:
      # - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
      - CLI_ARGS=--allow-code --medvram --xformers --api --api-auth baizhi958216:baizhi958216 --enable-insecure-extension-access
    container_name: auto
    ports:
      - "7861:7860"
    volumes:
      - ./data:/data
      - ./output:/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  open-webui:
  ollama:
  auto: